# Generated by Django 2.1.2 on 2018-10-05 11:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('test_shop_app', '0004_auto_20181005_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Basket',
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='BasketItem',
        ),
    ]
