# Generated by Django 2.1.2 on 2018-10-05 11:50

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('test_shop_app', '0005_auto_20181005_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='BasketItem',
            new_name='CartItem',
        ),
    ]
