# Generated by Django 2.1.2 on 2018-10-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_shop_app', '0008_auto_20181009_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='shop',
            name='time',
            field=models.TextField(blank=True, verbose_name='Время работы'),
        ),
    ]
