# Generated by Django 2.1.2 on 2018-10-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_shop_app', '0010_auto_20181009_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='mapurl',
            field=models.TextField(blank=True, verbose_name='Скрипт карты'),
        ),
    ]
