# Generated by Django 2.1.2 on 2018-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_shop_app', '0007_auto_20181009_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='store_1', max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='manager_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Имя упр.'),
        ),
    ]
