# Generated by Django 2.1.2 on 2018-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_shop_app', '0015_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='kekvald@yandex.ru', max_length=254),
        ),
    ]
