# Generated by Django 2.1.2 on 2018-10-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_shop_app', '0016_auto_20181010_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
