# Generated by Django 2.1.2 on 2018-10-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_shop_app', '0018_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='basket_total',
            new_name='cart_total',
        ),
    ]
