# Generated by Django 2.1.2 on 2018-10-12 08:50

from django.db import migrations, models
import test_shop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_shop_app', '0019_auto_20181011_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to=test_shop_app.models.image_folder, verbose_name='Изображение товара'),
        ),
    ]
